version: '3.8'

services:
  web_alvarezplacas:
    build: .
    container_name: alvarezplacas_web
    restart: always
    ports:
      - "4322:80"
    networks:
      - javiermix_network

networks:
  javiermix_network:
    external: true
